# Generated by Django 4.2.7 on 2025-10-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAnomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('', '— selecione —'), ('DESVIO', 'Desvio'), ('NAO_CONFORMIDADE', 'Não Conformidade'), ('INCIDENTE_ALTO_POTENCIAL', 'Incidente Alto Potencial'), ('ACIDENTE', 'Acidente')], max_length=30, verbose_name='Tipo')),
                ('siteInstalacao', models.CharField(help_text='Formato: [tipo] [Nome da embarcação]', max_length=100, verbose_name='Site/Instalação')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('subcontratada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subcontratada')),
                ('subcontratadaNaoAplicavel', models.BooleanField(default=False, verbose_name='Subcontratada Não Aplicável')),
                ('dataEvento', models.DateField(verbose_name='Data do Evento')),
                ('horarioEvento', models.TimeField(verbose_name='Horário do Evento')),
                ('municipioUF', models.CharField(choices=[('RIO_DE_JANEIRO_RJ', 'Rio de Janeiro – RJ'), ('MACAE_RJ', 'Macaé – RJ'), ('SAO_JOAO_DA_BARRA_RJ', 'S. João da Barra – RJ'), ('VITORIA_ES', 'Vitória – ES'), ('BACIA_CAMPOS_OFFSHORE', 'Bacia de Campos – Offshore'), ('BACIA_SANTOS_OFFSHORE', 'Bacia de Santos – Offshore'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Município/UF')),
                ('municipioOutro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Outro Município')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('relacaoEvento', models.CharField(choices=[('PESSOAS', 'Pessoas'), ('EMBARCACAO', 'Embarcação'), ('OPERACAO', 'Operação')], max_length=15, verbose_name='Relação do Evento')),
                ('acoesAdotadas', models.TextField(max_length=2000, verbose_name='Ações Adotadas')),
                ('ordemServico1', models.CharField(blank=True, max_length=13, verbose_name='Ordem de Serviço 1')),
                ('ordemServico2', models.CharField(blank=True, max_length=50, verbose_name='Ordem de Serviço 2')),
                ('operacaoParalisada', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Operação/Instalação Paralisada?')),
                ('sistemaDegradado', models.CharField(blank=True, max_length=3, null=True, verbose_name='Embarcação operou com sistema degradado?')),
                ('embarcacaoDerivou', models.CharField(blank=True, max_length=3, null=True, verbose_name='Embarcação derivou?')),
                ('embarcacaoPerdeuPosicao', models.CharField(blank=True, max_length=3, null=True, verbose_name='Embarcação perdeu posição?')),
                ('informacoesComplementares', models.TextField(blank=True, max_length=2000, verbose_name='Informações Complementares')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informe de Anomalia',
                'verbose_name_plural': 'Informes de Anomalia',
                'ordering': ['-dataEvento', '-horarioEvento'],
            },
        ),
        migrations.CreateModel(
            name='SubTabPessoasAnomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('idade', models.CharField(max_length=4, verbose_name='Idade')),
                ('funcao', models.CharField(max_length=30, verbose_name='Função')),
                ('tempoExpFuncao', models.CharField(max_length=15, verbose_name='Tempo de experiência na função')),
                ('tempoExpEmpresa', models.CharField(max_length=15, verbose_name='Tempo de experiência na empresa')),
                ('duracaoUltimaFolga', models.CharField(max_length=12, verbose_name='Duração da última folga')),
                ('necessarioDesembarque', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Necessário Desembarque?')),
                ('resgateAeromedico', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Resgate Aeromédico?')),
                ('situacaoAtual', models.TextField(max_length=500, verbose_name='Situação Atual (estado de saúde)')),
                ('idxAnomalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='fiscweb.informeanomalia', verbose_name='Informe de Anomalia Pessoas')),
            ],
            options={
                'verbose_name': 'Pessoa Envolvida',
                'verbose_name_plural': 'Pessoas Envolvidas',
            },
        ),
    ]
