# Generated by Django 4.2.7 on 2025-11-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materialEmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descMatEmb', models.CharField(max_length=40, verbose_name='Descrição do Material')),
                ('identMatEmb', models.CharField(blank=True, max_length=15, null=True, verbose_name='Identificação/N.Série')),
                ('pesoMatEmb', models.IntegerField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('alturaMatEmb', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura (m)')),
                ('larguraMatEmb', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Largura (m)')),
                ('comprimentoMatEmb', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Comprimento (m)')),
                ('respEmbMat', models.CharField(blank=True, choices=[('CRD', 'CRD'), ('MIS', 'MIS'), ('CENPES', 'CENPES'), ('EQSE', 'EQSE'), ('ISBM', 'ISBM'), ('ANC', 'ANC'), ('OUTRO', 'Outro')], max_length=8, null=True, verbose_name='Responsável pelo Material')),
                ('outRespEmbMat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Outro Responsável')),
                ('contBordoEmbMat', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('N/A', 'N/A')], max_length=4, verbose_name='Material em contentor que ficará a bordo?')),
                ('descContMatEmb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição do contentor')),
                ('idContMatEmb', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificação do Contentor')),
                ('respContMatEmb', models.CharField(blank=True, choices=[('CRD', 'CRD'), ('LOEP', 'LOEP')], max_length=6, null=True, verbose_name='Responsável pelo Contentor')),
                ('certContMatEmb', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero do Certificado do Contentor')),
                ('valContMatEmb', models.DateField(blank=True, null=True, verbose_name='Validade do Certificado do Contentor')),
                ('obsMatEmb', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('statusProgMatEmb', models.CharField(blank=True, choices=[('', ''), ('EMBARQUE PROGRAMADO', 'EMBARQUE PROGRAMADO'), ('MATERIAL A BORDO', 'MATERIAL A BORDO'), ('EMBARQUE NÃO CONCLUIDO', 'EMBARQUE NÃO CONCLUIDO'), ('APLICADO NA OPERAÇÃO', 'APLICADO NA OPERAÇÃO'), ('RELACIONADO PARA DESEMBARQUE', 'RELACIONADO PARA DESEMBARQUE'), ('DESEMBARQUE SOLICITADO', 'DESEMBARQUE SOLICITADO'), ('DESEMBARQUE PROGRAMADO', 'DESEMBARQUE PROGRAMADO'), ('DESEMBARQUE NÃO CONCLUIDO', 'DESEMBARQUE NÃO CONCLUIDO'), ('MATERIAL DESEMBARCADO', 'MATERIAL DESEMBARCADO')], default='', max_length=30, verbose_name='Status do Material')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('barcoMatEmb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscweb.barcoscad', verbose_name='Embarcação')),
            ],
            options={
                'verbose_name': 'Material - Programação de Embarque',
                'verbose_name_plural': 'Materiais - Programação de Embarque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='subMatEmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPrevEmbMat', models.DateField(verbose_name='Data Prevista para embarque')),
                ('numRtMatEmb', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da RT de Embarque')),
                ('numNotaFiscMatEmb', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da Nota Fiscal')),
                ('meioRecEmbMat', models.CharField(blank=True, choices=[('PORTO', 'PORTO'), ('TRANSBORDO UEP', 'TRANSBORDO UEP'), ('TRANSBORDO BARCO', 'TRANSBORDO BARCO'), ('RETIRADO DE OS', 'RETIRADO DE OS')], max_length=20, null=True, verbose_name='Meio de recebimento')),
                ('uepRecMatEmb', models.CharField(blank=True, max_length=20, null=True, verbose_name='UEP transbordo')),
                ('misBarcoFlag', models.BooleanField(default=True, verbose_name='Barco MIS?')),
                ('misBarcoRecMatEmb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Barco MIS transbordo')),
                ('barcoRecMatEmb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Barco Não MIS Transbordo')),
                ('osEmbMat', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ordem de Serviço')),
                ('statusRegEmb', models.CharField(blank=True, default='', max_length=30, verbose_name='Status do registro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('idxMatEmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='fiscweb.materialemb')),
            ],
            options={
                'verbose_name': 'Subtabela - Embarque Material',
                'verbose_name_plural': 'Subtabelas - Embarque Materiais',
                'ordering': ['-dataPrevEmbMat'],
            },
        ),
        migrations.CreateModel(
            name='subMatDesemb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPrevDesmbMat', models.DateField(verbose_name='Data Prevista para Desembarque')),
                ('meioEnvDesmbMat', models.CharField(blank=True, choices=[('PORTO', 'PORTO'), ('TRANSBORDO UEP', 'TRANSBORDO UEP'), ('TRANSBORDO BARCO', 'TRANSBORDO BARCO'), ('APLICADO A OS', 'APLICADO A OS')], max_length=20, null=True, verbose_name='Meio de Envio')),
                ('uepDesembMatEmb', models.CharField(blank=True, max_length=20, null=True, verbose_name='UEP transbordo')),
                ('misBarcoFlagDesemb', models.BooleanField(default=True, verbose_name='Barco MIS?')),
                ('misBarcoDesembMatEmb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Barco MIS transbordo')),
                ('barcoDesembMatEmb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Barco Não MIS Transbordo')),
                ('osRecDesembMat', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ordem de serviço')),
                ('numRtMatDesemb', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da RT de Desembarque')),
                ('numNotaFiscMatDesemb', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da Nota Fiscal')),
                ('statusRegDesemb', models.CharField(blank=True, default='', max_length=30, verbose_name='Status do registro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('idxMatDesemb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desembarques', to='fiscweb.materialemb')),
            ],
            options={
                'verbose_name': 'Subtabela - Desembarque Material',
                'verbose_name_plural': 'Subtabelas - Desembarque Materiais',
                'ordering': ['-dataPrevDesmbMat'],
            },
        ),
    ]
