# Generated by Django 4.2.7 on 2025-09-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0001_initial'),
    ]

    operations = [
    ]
