# Generated by Django 4.2.7 on 2025-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeanomalia',
            name='dataEnvioInforme',
            field=models.DateField(blank=True, verbose_name='Data do envio'),
        ),
        migrations.AlterField(
            model_name='informeanomalia',
            name='destInforme',
            field=models.TextField(blank=True, max_length=400, verbose_name='Destinatários do Informe'),
        ),
        migrations.AlterField(
            model_name='informeanomalia',
            name='horaEnvioInforme',
            field=models.TimeField(blank=True, verbose_name='Hora do envio'),
        ),
    ]
