# Generated by Django 4.2.7 on 2025-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0002_materialemb_submatemb_submatdesemb'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsSolicDesemb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailMatCrd', models.TextField(blank=True, max_length=200, null=True, verbose_name='E-mails materiais CRD')),
                ('emailMatMis', models.TextField(blank=True, max_length=200, null=True, verbose_name='E-mails materiais MIS')),
                ('emailsMatCc', models.TextField(blank=True, max_length=200, null=True, verbose_name='E-mails materiais C-C')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-mail Solicitação Desembarque',
                'verbose_name_plural': 'E-mails Solicitação Desembarque',
            },
        ),
    ]
