# Generated by Django 4.2.7 on 2025-09-28 00:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscweb', '0002_auto_20250927_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscaisCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=4, unique=True, verbose_name='Chave')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (99)99999-9999', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')], verbose_name='Celular')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal',
                'verbose_name_plural': 'Fiscais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModalBarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(max_length=4, verbose_name='Modal')),
            ],
            options={
                'verbose_name': 'Modal',
                'verbose_name_plural': 'Modais',
            },
        ),
        migrations.CreateModel(
            name='PassServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPS', models.CharField(max_length=8, verbose_name='Numero')),
                ('dataInicio', models.DateField(verbose_name='Inicio da Quinzena')),
                ('dataFim', models.DateField(verbose_name='Fim da Quinzena')),
                ('dataEmissao', models.DateField(verbose_name='Emissao')),
                ('BarcoPS', models.CharField(max_length=15, verbose_name='Numero')),
                ('statusPS', models.CharField(max_length=12, verbose_name='Empresa Navegação')),
                ('fiscalEmb', models.CharField(max_length=20, unique=True, verbose_name='ICJ Empresa Navegação')),
                ('fiscalDes', models.CharField(max_length=80, verbose_name='Empresa Serviço')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passagem de Serviço',
                'verbose_name_plural': 'Passagens de serviço',
                'ordering': ['numPS'],
            },
        ),
        migrations.CreateModel(
            name='TipoBarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=4, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='BarcosCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_B', models.CharField(max_length=4, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('modal_B', models.CharField(max_length=4, verbose_name='Modal')),
                ('email_BR', models.EmailField(max_length=40, unique=True, verbose_name='E-mail Petrobras')),
                ('data_pr_porto', models.DateField(verbose_name='Data Primeiro Porto')),
                ('empr_nav', models.CharField(max_length=80, verbose_name='Empresa Navegação')),
                ('icj_empr_nav', models.CharField(max_length=20, unique=True, verbose_name='ICJ Empresa Navegação')),
                ('empr_serv', models.CharField(max_length=80, verbose_name='Empresa Serviço')),
                ('icj_empr_serv', models.CharField(max_length=20, unique=True, verbose_name='ICJ Empresa Serviço')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modal_sel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscweb.modalbarco', verbose_name='Seleciona Modal')),
                ('tipo_sel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscweb.tipobarco', verbose_name='Sleciona Tipo')),
            ],
            options={
                'verbose_name': 'Barco',
                'verbose_name_plural': 'Barcos',
                'ordering': ['nome'],
            },
        ),
    ]
