# Generated by Django 4.2.7 on 2025-10-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0003_alter_informeanomalia_dataenvioinforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoscad',
            name='emailFiscContr',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='E-mail Fiscal-Contratada'),
        ),
    ]
