# Generated by Django 4.2.7 on 2025-09-28 23:25

from django.db import migrations, models
import django.db.models.deletion
import fiscweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anocSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevanocSMS', models.BooleanField(default=False, verbose_name='Anomalias?')),
                ('DataanocSMS', models.DateField(verbose_name='Data da Anomalia')),
                ('classnocSMS', models.CharField(choices=[('critica', 'CRÍTICA'), ('nao_critica', 'NÃO CRITICA')], max_length=12, verbose_name='Classificação da Anomalia')),
                ('DescanocSMS', models.TextField(blank=True, max_length=500, verbose_name='Descrição da Anomalia')),
                ('informContr', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], max_length=4, verbose_name='Houve Informe ao Controle?')),
            ],
            options={
                'verbose_name': 'Anomalia e Ocorrência de SMS',
                'verbose_name_plural': 'Anomalias e Ocorrêcias de SMS',
                'ordering': ['idxanocSMS__BarcoPS', '-idxanocSMS__numPS'],
            },
        ),
        migrations.CreateModel(
            name='iapo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priDomIapo', models.DateField(verbose_name='IAPO Primeira Semana')),
                ('priDomIapoOs', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('n_ap', 'N/A')], max_length=4, verbose_name='OSs para IAPO?')),
                ('segDomIapo', models.DateField(verbose_name='IAPO Segunda Semana')),
                ('segDomIapoOs', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('n_ap', 'N/A')], max_length=4, verbose_name='OSs para IAPO?')),
                ('terDomIapo', models.DateField(verbose_name='IAPO Terceira Semana')),
                ('terDomIapoOsConc', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('n_ap', 'N/A')], max_length=4, verbose_name='OSs concluidas para esse envio?')),
                ('ObservIapo', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'IAPO',
                'ordering': ['idxIapo__BarcoPS', '-idxIapo__numPS'],
            },
        ),
        migrations.CreateModel(
            name='inoPendContr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previnoPendContr', models.BooleanField(default=False, verbose_name='Anomalias?')),
                ('DatainoPendContr', models.DateField(verbose_name='Data da Anomalia')),
                ('DescinoPendContr', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('BroainoPendContr', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('n_ap', 'N/A')], max_length=4, verbose_name='Abertura de BROA?')),
                ('NumBroainoPendContr', models.CharField(blank=True, max_length=12, verbose_name='Num BROA')),
                ('infGerContinoPendContr', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('n_ap', 'N/A')], max_length=4, verbose_name='Houve Informe a Gerência de Contrato?')),
            ],
            options={
                'verbose_name': 'Inoperância,Pendencia e Assunto Contratual',
                'verbose_name_plural': 'Inoperâncias,Pendencias e Assuntos Contratuais',
                'ordering': ['idxinoPendContr__BarcoPS', '-idxinoPendContr__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoAbast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevAbast', models.BooleanField(default=False, verbose_name='Abastecimento previsto?')),
                ('OrdSerAbast', models.CharField(max_length=12, verbose_name='Ordem de Serviço')),
                ('DataHoraPrevAbast', models.DateTimeField(verbose_name='Data e Hora Prevista')),
                ('QuantAbast', models.IntegerField(verbose_name='Quantidade (m³)')),
                ('DuracPrev', models.IntegerField(verbose_name='Duração Prevista(h)')),
                ('UltAbast', models.DateField(verbose_name='Último Abastecimento')),
                ('Anexos', models.FileField(upload_to=fiscweb.models.caminho_PS, verbose_name='Anexos')),
                ('ObservManPrev', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Abastecimento - Porto',
                'verbose_name_plural': 'Abastecimentos - Portos',
                'ordering': ['idxPortoAB__BarcoPS', '-idxPortoAB__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoDesMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevDesMat', models.BooleanField(default=False, verbose_name='Desembarque de Materiais?')),
                ('OsDesMat', models.CharField(max_length=12, verbose_name='OS de Origem')),
                ('RtDesMat', models.CharField(max_length=12, verbose_name='Num RT')),
                ('ObservDesMat', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('Anexos', models.FileField(upload_to=fiscweb.models.caminho_PS, verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Desembarque Material - Porto',
                'verbose_name_plural': 'Desembarque Materiais - Portos',
                'ordering': ['idxPortoDM__BarcoPS', '-idxPortoDM__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoEmbEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevEmbEquip', models.BooleanField(default=False, verbose_name='Embarque de Equipe?')),
                ('DescEmbEquip', models.CharField(choices=[('crd', 'CRD'), ('stc', 'STC'), ('eqse', 'EQSE'), ('sto', 'STO'), ('cenpes', 'CENPES'), ('ambient', 'AMBIENTAÇÃO'), ('outros', 'OUTROS')], max_length=9, verbose_name='Descrição')),
                ('equipNome', models.CharField(max_length=30, verbose_name='Nome')),
                ('equipEmpre', models.CharField(max_length=30, verbose_name='Empresa')),
                ('ObservEmbEquip', models.TextField(blank=True, max_length=200, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Embarque Equipe - Porto',
                'verbose_name_plural': 'Embarque Equipes - Portos',
                'ordering': ['idxPortoEE__BarcoPS', '-idxPortoEE__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoEmbMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevEmbMat', models.BooleanField(default=False, verbose_name='Embarque de Materiais?')),
                ('OsEmbMat', models.CharField(max_length=12, verbose_name='OS de Destino')),
                ('RtEmbMat', models.CharField(max_length=12, verbose_name='Num RT')),
                ('ObservEmbMat', models.TextField(blank=True, max_length=200, verbose_name='Observações')),
                ('Anexos', models.FileField(upload_to=fiscweb.models.caminho_PS, verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Embarque Material - Porto',
                'verbose_name_plural': 'Embarque Materiais - Portos',
                'ordering': ['idxPortoEM__BarcoPS', '-idxPortoEM__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoInspNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevInsNorm', models.BooleanField(default=False, verbose_name='Inspeção Normativa?')),
                ('DescInspNorm', models.CharField(choices=[('anvisa', 'ANVISA'), ('classe', 'CLASSE'), ('marinha', 'MARINHA'), ('outros', 'OUTROS')], max_length=9, verbose_name='Inspeções Normativas')),
                ('OrdSerInspNorm', models.CharField(max_length=12, verbose_name='Ordem de Serviço')),
                ('ObservInspNorm', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Inspeção Normativa - Porto',
                'verbose_name_plural': 'Inspeções Normativas - Portos',
                'ordering': ['idxPortoIN__BarcoPS', '-idxPortoIN__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoInspPetr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevInspPetr', models.BooleanField(default=False, verbose_name='Inspeção Petrobras?')),
                ('DescInspPetr', models.CharField(choices=[('gsopsms', 'GSOP/SMS'), ('gercontr', 'GERENCIA CONTRATO'), ('geroper', 'GERENTE OPERACIONAL'), ('sto', 'STO'), ('outros', 'OUTROS')], max_length=9, verbose_name='Inspeções Petrobras')),
                ('auditorPetr', models.CharField(max_length=30, verbose_name='Auditor/Visitante')),
                ('gerAuditorPetr', models.CharField(max_length=30, verbose_name='Gerencia')),
                ('ObservInspPetr', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Inspeção Petrobras - Porto',
                'verbose_name_plural': 'Inspeções Petrobras - Portos',
                'ordering': ['idxPortoIP__BarcoPS', '-idxPortoIP__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoManutPrev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevManPrev', models.BooleanField(default=False, verbose_name='Manutenção preventiva prevista?')),
                ('Franquia', models.IntegerField(verbose_name='Franquia solicitada')),
                ('SaldoFranquia', models.IntegerField(verbose_name='Saldo de Franquia')),
                ('OrdSerManutPrev', models.CharField(max_length=12, verbose_name='Ordem de Serviço')),
                ('Rade', models.FileField(upload_to=fiscweb.models.caminho_PS, verbose_name='Anexo Rade')),
                ('ObservManPrev', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Manutenção Preventiva - Porto',
                'verbose_name_plural': 'Manutenções Preventivas - Portos',
                'ordering': ['idxPortoMP__BarcoPS', '-idxPortoMP__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoMobD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevMobD', models.BooleanField(default=False, verbose_name='Mobilização ou Desmobilização?')),
                ('OsMobD', models.CharField(max_length=12, verbose_name='OS de Origem')),
                ('ObservMobD', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'MObilização e Desmobilização - Porto',
                'verbose_name_plural': 'Mobilizações Desmobilizações - Portos',
                'ordering': ['idxPortoMobD__BarcoPS', '-idxPortoMobD__numPS'],
            },
        ),
        migrations.CreateModel(
            name='PortoTrocaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porto', models.CharField(max_length=40, verbose_name='Porto')),
                ('Terminal', models.CharField(max_length=40, verbose_name='Terminal')),
                ('OrdSerPorto', models.CharField(max_length=12, verbose_name='Ordem de Serviço')),
                ('AtracPorto', models.DateField(verbose_name='Horario da Atracação')),
                ('DuracPorto', models.CharField(max_length=6, verbose_name='Duração da estadia(h)')),
                ('ObservPorto', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Troca de Turma - Porto',
                'verbose_name_plural': 'Trocas de Turma - Portos',
                'ordering': ['idxPortoTT__BarcoPS', '-idxPortoTT__numPS'],
            },
        ),
        migrations.AlterModelOptions(
            name='barcoscad',
            options={'ordering': ['nomeBarco'], 'verbose_name': 'Barco', 'verbose_name_plural': 'Barcos'},
        ),
        migrations.AlterModelOptions(
            name='passserv',
            options={'ordering': ['BarcoPS', '-numPS'], 'verbose_name': 'Passagem de Serviço', 'verbose_name_plural': 'Passagens de serviço'},
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='data_pr_porto',
            new_name='dataPrimPorto',
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='email_BR',
            new_name='emailPetr',
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='empr_nav',
            new_name='emprNav',
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='empr_serv',
            new_name='emprServ',
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='icj_empr_nav',
            new_name='icjEmprNav',
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='icj_empr_serv',
            new_name='icjEmprServ',
        ),
        migrations.RenameField(
            model_name='barcoscad',
            old_name='modal_sel',
            new_name='modalSelec',
        ),
        migrations.RemoveField(
            model_name='barcoscad',
            name='modal_B',
        ),
        migrations.RemoveField(
            model_name='barcoscad',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='barcoscad',
            name='tipo_B',
        ),
        migrations.RemoveField(
            model_name='barcoscad',
            name='tipo_sel',
        ),
        migrations.RemoveField(
            model_name='passserv',
            name='dataEmissao',
        ),
        migrations.AddField(
            model_name='barcoscad',
            name='modalBarco',
            field=models.CharField(default=1, max_length=20, verbose_name='Modal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcoscad',
            name='nomeBarco',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcoscad',
            name='tipoBarco',
            field=models.CharField(choices=[('rsv', 'RSV'), ('sdsv', 'SDSV'), ('dsv', 'DSV'), ('tup', 'TUP')], default=1, max_length=6, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passserv',
            name='TipoBarco',
            field=models.CharField(default=1, max_length=6, verbose_name='Barco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passserv',
            name='anoPS',
            field=models.CharField(default=1, max_length=5, verbose_name='Ano da PS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passserv',
            name='dataEmissaoPS',
            field=models.DateField(default='2025-01-01', verbose_name='Data de Emissao'),
        ),
        migrations.AlterField(
            model_name='modalbarco',
            name='modal',
            field=models.CharField(max_length=20, verbose_name='Modal'),
        ),
        migrations.AlterField(
            model_name='passserv',
            name='BarcoPS',
            field=models.CharField(max_length=30, verbose_name='Barco'),
        ),
        migrations.AlterField(
            model_name='passserv',
            name='fiscalDes',
            field=models.CharField(max_length=30, verbose_name='Fiscal Desembarcando'),
        ),
        migrations.AlterField(
            model_name='passserv',
            name='fiscalEmb',
            field=models.CharField(max_length=30, verbose_name='Fiscal Embarcando'),
        ),
        migrations.AlterField(
            model_name='passserv',
            name='numPS',
            field=models.IntegerField(verbose_name='Numero da PS'),
        ),
        migrations.AlterField(
            model_name='passserv',
            name='statusPS',
            field=models.CharField(max_length=12, verbose_name='Status da PS'),
        ),
        migrations.DeleteModel(
            name='TipoBarco',
        ),
        migrations.AddField(
            model_name='portotrocaturma',
            name='idxPortoTT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portomobd',
            name='idxPortoMobD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portomanutprev',
            name='idxPortoMP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portoinsppetr',
            name='idxPortoIP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portoinspnorm',
            name='idxPortoIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portoembmat',
            name='idxPortoEM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portoembequip',
            name='idxPortoEE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portodesmat',
            name='idxPortoDM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='portoabast',
            name='idxPortoAB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='inopendcontr',
            name='idxinoPendContr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='iapo',
            name='idxIapo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
        migrations.AddField(
            model_name='anocsms',
            name='idxanocSMS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv'),
        ),
    ]
