# Generated by Django 4.2.7 on 2025-11-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0003_emailssolicdesemb'),
    ]

    operations = [
        migrations.CreateModel(
            name='portoMatDesemb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descMatDesembPs', models.CharField(blank=True, max_length=40, null=True, verbose_name='Descrição do Material')),
                ('numRtMatDesembPs', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero RT')),
                ('osMatDesembPs', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ordem de Serviço')),
                ('respMatDesembPs', models.CharField(blank=True, max_length=8, null=True, verbose_name='Responsavel Material')),
                ('descContMatDesembPs', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição do Contentor')),
                ('statusProgMatEmbPs', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status do Material')),
                ('dataPrevDesembMatPs', models.DateField(blank=True, null=True, verbose_name='Data Desembarque')),
                ('idxPortoMatDesemb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'Desembarque Material - Porto',
                'verbose_name_plural': 'Desembarque Materiais - Porto',
                'ordering': ['idxPortoMatDesemb__BarcoPS', '-idxPortoMatDesemb__numPS'],
            },
        ),
        migrations.CreateModel(
            name='portoMatEmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descMatEmbPs', models.CharField(blank=True, max_length=40, null=True, verbose_name='Descrição do Material')),
                ('numRtMatEmbPs', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero RT')),
                ('osMatEmbPs', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ordem de Serviço')),
                ('respMatEmbPs', models.CharField(blank=True, max_length=8, null=True, verbose_name='Responsavel Material')),
                ('descContMatEmbPs', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição do Contentor')),
                ('dataPrevEmbMatPs', models.DateField(blank=True, null=True, verbose_name='Data Embarque')),
                ('idxPortoMatEmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'Embarque Material - Porto',
                'verbose_name_plural': 'Embarque Materiais - Porto',
                'ordering': ['idxPortoMatEmb__BarcoPS', '-idxPortoMatEmb__numPS'],
            },
        ),
        migrations.RemoveField(
            model_name='portoembmat',
            name='idxPortoEM',
        ),
        migrations.RemoveField(
            model_name='subtabportoembmat',
            name='idxSubTabPortoEM',
        ),
        migrations.DeleteModel(
            name='PortoDesMat',
        ),
        migrations.DeleteModel(
            name='PortoEmbMat',
        ),
        migrations.DeleteModel(
            name='subTabPortoEmbMat',
        ),
    ]
