# Generated by Django 4.2.7 on 2025-09-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0004_anocsms_iapo_inopendcontr_portoabast_portodesmat_and_more'),
    ]

    operations = [
    ]
