# Generated by Django 4.2.7 on 2025-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0004_portomatdesemb_portomatemb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submatemb',
            name='idxMatEmb',
        ),
        migrations.AddField(
            model_name='materialemb',
            name='barcoRecMatEmb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Barco Não MIS Transbordo'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='dataPrevEmbMat',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista para embarque'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='meioRecEmbMat',
            field=models.CharField(blank=True, choices=[('PORTO', 'PORTO'), ('TRANSBORDO UEP', 'TRANSBORDO UEP'), ('TRANSBORDO BARCO', 'TRANSBORDO BARCO'), ('RETIRADO DE OS', 'RETIRADO DE OS')], max_length=20, null=True, verbose_name='Meio de recebimento'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='misBarcoFlag',
            field=models.BooleanField(default=True, verbose_name='Barco MIS?'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='misBarcoRecMatEmb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Barco MIS transbordo'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='numNotaFiscMatEmb',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='numRtMatDesemb',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da RT de Desembarque'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='numRtMatEmb',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero da RT de Embarque'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='osEmbMat',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ordem de Serviço'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='statusRegEmb',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Status do registro'),
        ),
        migrations.AddField(
            model_name='materialemb',
            name='uepRecMatEmb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UEP transbordo'),
        ),
        migrations.DeleteModel(
            name='subMatDesemb',
        ),
        migrations.DeleteModel(
            name='subMatEmb',
        ),
    ]
