# Generated by Django 4.2.7 on 2025-10-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0004_alter_barcoscad_emailfisccontr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoscad',
            name='emailAto',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='E-mail ATO'),
        ),
        migrations.AlterField(
            model_name='barcoscad',
            name='emailSto',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='E-mail STO'),
        ),
    ]
