# Generated by Django 4.2.7 on 2025-10-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0005_alter_barcoscad_emailato_alter_barcoscad_emailsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoscad',
            name='emailAto',
            field=models.EmailField(default=0, max_length=40, unique=True, verbose_name='E-mail ATO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barcoscad',
            name='emailSto',
            field=models.EmailField(default=0, max_length=40, unique=True, verbose_name='E-mail STO'),
            preserve_default=False,
        ),
    ]
