# Generated by Django 4.2.7 on 2025-10-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0005_auto_20250928_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaiscad',
            name='perfAdm',
            field=models.BooleanField(default=False, verbose_name='Perfil ADM?'),
        ),
        migrations.AddField(
            model_name='fiscaiscad',
            name='perfFisc',
            field=models.BooleanField(default=False, verbose_name='Perfil Fiscal?'),
        ),
        migrations.AlterField(
            model_name='barcoscad',
            name='tipoBarco',
            field=models.CharField(choices=[('RSV', 'RSV'), ('SDSV', 'SDSV'), ('DSV', 'DSV'), ('TUP', 'TUP')], max_length=6, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='smsLvSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LvSegCamoAsogUlt', models.DateField(verbose_name='Data da Última LV CAMO/ASOG')),
                ('LvSegCamoAsogProx', models.DateField(verbose_name='Data da Próxima LV CAMO/ASOG')),
                ('LvlSegCamoAsogFarol', models.CharField(max_length=3, verbose_name='Farol LV CAMO/ASOG')),
                ('LvSegCondNavioCpUlt', models.DateField(verbose_name='Data da Última LV Condição Navio(Curto Prazo)')),
                ('LvSegCondNavioCpProx', models.DateField(verbose_name='Data da Próxima LV Condição Navio(Curto Prazo)')),
                ('LvSegCondNavioCpFarol', models.DateField(verbose_name='Farol LV Condição Navio(Curto Prazo)')),
                ('LvlSegCondNavioLpUlt', models.DateField(verbose_name='Data da Última LV Condição Navio(Longo Prazo)')),
                ('LvSegCondNavioLpProx', models.DateField(verbose_name='Data da Próxima LV Condição Navio(Longo Prazo)')),
                ('LvSegCondNavioLpFarol', models.DateField(verbose_name='Farol LV Condição Navio(Longo Prazo)')),
                ('LvSegEspConfUlt', models.DateField(verbose_name='Data da Última LV Espaço Confinado')),
                ('LvSegEspConfProx', models.DateField(verbose_name='Data da Próxima LV Espaço Confinado')),
                ('LvSegEspConfFarol', models.CharField(max_length=3, verbose_name='Farol LV Espaço Confinado')),
                ('LvSegMovCargasUlt', models.DateField(verbose_name='Data da Última LV Movimentação de Cargas')),
                ('LvSegMovCargasProx', models.DateField(verbose_name='Data da Próxima LV Movimentação de Cargas')),
                ('LvSegMovCargasFarol', models.CharField(max_length=3, verbose_name='Farol LV Movimentação de Cargas')),
                ('LvSegPintQuimPerUlt', models.DateField(verbose_name='Data da Última LV Pintura e Produtos Químicos Perigosos')),
                ('LvSegPintQuimPerProx', models.DateField(verbose_name='Data da Próxima LV Pintura e Produtos Químicos Perigosos')),
                ('LvSegPintQuimPerFarol', models.CharField(max_length=3, verbose_name='Farol LV Pintura e Produtos Químicos Perigosos')),
                ('LvSegProcVcpUlt', models.DateField(verbose_name='Data da Última LV de Processo de VCP')),
                ('LvSegProcVcpProx', models.DateField(verbose_name='Data da Próxima LV de Processo de VCP')),
                ('LvSegProcVcpFarol', models.CharField(max_length=3, verbose_name='Farol LV de Processo de VCP')),
                ('LvlSegRespEmergUlt', models.DateField(verbose_name='Data da Última LV de Resposta a Emergência')),
                ('LvSegRespEmergProx', models.DateField(verbose_name='Data da Próxima LV de Resposta a Emergência')),
                ('LvSegRespEmergFarol', models.CharField(max_length=3, verbose_name='Farol LV de Resposta a Emergência')),
                ('LvlSegRiscSanitUlt', models.DateField(verbose_name='Data da Última LV de Risco Sanitário')),
                ('LvSegRiscSanitProx', models.DateField(verbose_name='Data da Próxima LV de Risco Sanitário')),
                ('LvSegRiscSanitFarol', models.CharField(max_length=3, verbose_name='Farol LV de Risco Sanitário')),
                ('LvSegTestHidrostUlt', models.DateField(verbose_name='Data da Última LV de Teste Hidrostático')),
                ('LvSegTestHidrostProx', models.DateField(verbose_name='Data da Próxima LV de Teste Hidrostático')),
                ('LvSegTestHidrostFarol', models.CharField(max_length=3, verbose_name='Farol LV de Teste Hidrostático')),
                ('LvlSegTrabQuentUlt', models.DateField(verbose_name='Data da Última LV de Trabalho a Quente')),
                ('LvSegTrabQuentProx', models.DateField(verbose_name='Data da Próxima LV de Trabalho a Quente')),
                ('LvSegTrabQuentFarol', models.CharField(max_length=3, verbose_name='Farol LV de Trabalho a Quente')),
                ('LvlSegTrabAltUlt', models.DateField(verbose_name='Data da Última LV de Trabalho em Altura')),
                ('LvSegTrabAltProx', models.DateField(verbose_name='Data da Próxima LV de Trabalho em Altura')),
                ('LvSegTrabAltFarol', models.CharField(max_length=3, verbose_name='Farol LV de Trabalho em Altura')),
                ('LvlSegTrabEletrUlt', models.DateField(verbose_name='Data da Última LV de Trabalho em eletricidade')),
                ('LvSegTrabEletrProx', models.DateField(verbose_name='Data da Próxima LV de Trabalho em eletricidade')),
                ('LvSegTrabEletrFarol', models.CharField(max_length=3, verbose_name='Farol LV de Trabalho em eletricidade')),
                ('obsLvSeg', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('idxsmsLvSeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'LV de Segurança',
                'verbose_name_plural': 'LVs de Segurança',
                'ordering': ['idxsmsLvSeg__BarcoPS', '-idxsmsLvSeg__numPS'],
            },
        ),
        migrations.CreateModel(
            name='smsLvMang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataUltLvMang', models.DateField(verbose_name='Data da Última LV')),
                ('dataProxLvMang', models.DateField(verbose_name='Data da Próxima LV')),
                ('obsLvMang', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('idxsmsLvMang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'LV de Mangueiras',
                'verbose_name_plural': 'LVs de Mangueiras',
                'ordering': ['idxsmsLvMang__BarcoPS', '-idxsmsLvMang__numPS'],
            },
        ),
    ]
