# Generated by Django 4.2.7 on 2025-11-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0005_remove_submatemb_idxmatemb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assunPendContr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistroInicial', models.DateField(blank=True, null=True, verbose_name='Data Regitro Inicial')),
                ('fiscRegistroInicial', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fiscal Registro Inicial')),
                ('classeRegistroInicial', models.CharField(blank=True, choices=[('PENDENCIA DE ACEITAÇÃO', 'PENDENCIA DE ACEITAÇÃO'), ('ITENS CONTRATUAIS', 'ITENS CONTRATUAIS'), ('OUTROS', 'OUTROS')], max_length=30, null=True, verbose_name='Numero RT')),
                ('descrRegistroInicial', models.TextField(blank=True, max_length=400, verbose_name='Descrição')),
                ('mantRegistroInicial', models.BooleanField(default=True, verbose_name='Mantém ativo para proxima PS')),
            ],
            options={
                'verbose_name': 'Assunto e Pendência Contratual - Rotina',
                'verbose_name_plural': 'Assuntos e Penências Contratuais- Rotina',
                'ordering': ['-dataRegistroInicial', 'classeRegistroInicial'],
            },
        ),
        migrations.CreateModel(
            name='subAssunPendContr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistroComent', models.DateField(blank=True, null=True, verbose_name='Data Comentario')),
                ('fiscRegistroComent', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fiscal Registro Inicial')),
                ('descrRegistroComent', models.TextField(blank=True, max_length=400, verbose_name='Descrição')),
                ('idxAssunPendContr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.assunpendcontr')),
            ],
            options={
                'verbose_name': 'Comentario assunto e pendencia - Rotina',
                'verbose_name_plural': 'Comentários assuntos e pendências- Rotina',
                'ordering': ['-dataRegistroComent', 'idxAssunPendContr__classeRegistroInicial'],
            },
        ),
    ]
