# Generated by Django 4.2.7 on 2025-10-18 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0006_alter_barcoscad_emailato_alter_barcoscad_emailsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoscad',
            name='contAto',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (99)99999-9999', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')], verbose_name='Celular ATO'),
        ),
        migrations.AlterField(
            model_name='barcoscad',
            name='contSto',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (99)99999-9999', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')], verbose_name='Celular STO'),
        ),
    ]
