# Generated by Django 4.2.7 on 2025-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0006_assunpendcontr_subassunpendcontr'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunpendcontr',
            name='abertoBroa',
            field=models.BooleanField(default=False, verbose_name='Abertura de BROA?'),
        ),
        migrations.AddField(
            model_name='assunpendcontr',
            name='numeroBroa',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero do BROA'),
        ),
        migrations.DeleteModel(
            name='inoPendContr',
        ),
    ]
