# Generated by Django 4.2.7 on 2025-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0006_fiscaiscad_perfadm_fiscaiscad_perffisc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passserv',
            name='statusPS',
            field=models.CharField(choices=[('RASCUNHO', 'RASCUNHO'), ('FINALIZADA', 'FINALIZADA')], default='RASCUNHO', max_length=12, verbose_name='Status da PS'),
        ),
    ]
