# Generated by Django 4.2.7 on 2025-11-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0007_assunpendcontr_abertobroa_assunpendcontr_numerobroa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subassunpendcontr',
            name='idxAssunPendContr',
        ),
        migrations.DeleteModel(
            name='assunPendContr',
        ),
        migrations.DeleteModel(
            name='subAssunPendContr',
        ),
    ]
