# Generated by Django 4.2.7 on 2025-10-07 18:23

from django.db import migrations, models
import django.db.models.deletion
import fiscweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0007_alter_passserv_statusps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portoembequip',
            name='DescEmbEquip',
        ),
        migrations.RemoveField(
            model_name='portoembequip',
            name='equipEmpre',
        ),
        migrations.RemoveField(
            model_name='portoembequip',
            name='equipNome',
        ),
        migrations.RemoveField(
            model_name='portoembmat',
            name='Anexos',
        ),
        migrations.RemoveField(
            model_name='portoembmat',
            name='OsEmbMat',
        ),
        migrations.RemoveField(
            model_name='portoembmat',
            name='RtEmbMat',
        ),
        migrations.RemoveField(
            model_name='portoinspnorm',
            name='DescInspNorm',
        ),
        migrations.RemoveField(
            model_name='portoinspnorm',
            name='OrdSerInspNorm',
        ),
        migrations.RemoveField(
            model_name='portoinsppetr',
            name='DescInspPetr',
        ),
        migrations.RemoveField(
            model_name='portoinsppetr',
            name='auditorPetr',
        ),
        migrations.RemoveField(
            model_name='portoinsppetr',
            name='gerAuditorPetr',
        ),
        migrations.AddField(
            model_name='portoabast',
            name='QuantUltAbast',
            field=models.IntegerField(default=0, verbose_name='Quantidade Ultimo Abastecimento (m³)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smslvseg',
            name='LvSegCondNavioCpFarol',
            field=models.CharField(max_length=3, verbose_name='Farol LV Condição Navio(Curto Prazo)'),
        ),
        migrations.AlterField(
            model_name='smslvseg',
            name='LvSegCondNavioLpFarol',
            field=models.CharField(max_length=3, verbose_name='Farol LV Condição Navio(Longo Prazo)'),
        ),
        migrations.CreateModel(
            name='subTabPortoInspPetr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescInspPetr', models.CharField(choices=[('GSOP/SMS', 'GSOP/SMS'), ('GERENCIA CONTRATO', 'GERENCIA CONTRATO'), ('STEE', 'STEE'), ('GERENTE MIS', 'GERENTE MIS'), ('STO MIS', 'STO MIS'), ('OUTROS', 'OUTROS')], max_length=20, verbose_name='Descrição da visita')),
                ('auditorPetr', models.CharField(max_length=30, verbose_name='Auditor/Visitante')),
                ('gerAuditorPetr', models.CharField(max_length=30, verbose_name='Gerencia')),
                ('idxsubTabPortoIP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.portoinsppetr')),
            ],
            options={
                'verbose_name': 'Lista Inspeção Petrobras - Porto',
                'verbose_name_plural': 'Lista Inspeções Petrobras - Portos',
                'ordering': ['idxsubTabPortoIP__idxPortoIP__BarcoPS', '-idxsubTabPortoIP__idxPortoIP__numPS'],
            },
        ),
        migrations.CreateModel(
            name='subTabPortoInspNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescInspNorm', models.CharField(choices=[('anvisa', 'ANVISA'), ('classe', 'CLASSE'), ('marinha', 'MARINHA'), ('outros', 'OUTROS')], max_length=10, verbose_name='Inspeções Normativas')),
                ('OrdSerInspNorm', models.CharField(max_length=12, verbose_name='Ordem de Serviço')),
                ('idxsubTabPortoInspNorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.portoinspnorm')),
            ],
            options={
                'verbose_name': 'Lista Inspeção Normativa - Porto',
                'verbose_name_plural': 'Lista Inspeções Petrobras - Portos',
                'ordering': ['idxsubTabPortoInspNorm__idxPortoIN__BarcoPS', '-idxsubTabPortoInspNorm__idxPortoIN__numPS'],
            },
        ),
        migrations.CreateModel(
            name='subTabPortoEmbMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMatEmb', models.CharField(choices=[('MATERIAIS OP CRD', 'MATERIAIS OP CRD'), ('MATERIAIS OP MIS', 'MATERIAIS OP MIS'), ('CONTENTORES', 'CONTENTORES'), ('FERRAMENTAS', 'FERRAMENTAS'), ('MATERIAIS EQSE', 'MATERIAIS EQSE'), ('OUTROS', 'OUTROS')], max_length=30, verbose_name='Tipo de Material')),
                ('numSerMatEmb', models.CharField(max_length=30, verbose_name='Identificador ou Num Serie do Material')),
                ('matEmbDesc', models.CharField(max_length=300, verbose_name='Descrição do Material')),
                ('dataValCertLing', models.DateField(verbose_name='Data Validade Certificado Lingada-Olhais')),
                ('OsEmbMat', models.CharField(max_length=12, verbose_name='OS de Destino')),
                ('RtEmbMat', models.CharField(max_length=14, verbose_name='Num RT')),
                ('Anexos', models.FileField(upload_to=fiscweb.models.caminho_PS, verbose_name='Anexo')),
                ('idxSubTabPortoEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.portoembmat')),
            ],
            options={
                'verbose_name': 'Lista Embarque Material - Porto',
                'verbose_name_plural': 'Lista Embarque Materiais - Portos',
                'ordering': ['idxSubTabPortoEM__idxPortoEM__BarcoPS', '-idxSubTabPortoEM__idxPortoEM__numPS'],
            },
        ),
        migrations.CreateModel(
            name='subTabPortoEmbEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescEmbEquip', models.CharField(choices=[('CRD', 'CRD'), ('STC', 'STC'), ('EQSE', 'EQSE'), ('STO', 'STO'), ('CENPES', 'CENPES'), ('AMBIENTAÇÃO MIS', 'AMBIENTAÇÃO MIS'), ('OUTROS', 'OUTROS')], max_length=18, verbose_name='Descrição')),
                ('equipNome', models.CharField(max_length=30, verbose_name='Nome')),
                ('equipFuncao', models.CharField(max_length=30, verbose_name='Função')),
                ('equipEmpre', models.CharField(max_length=30, verbose_name='Empresa')),
                ('idxSubTabPortoEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.portoembequip')),
            ],
            options={
                'verbose_name': 'Lista Embarque Equipe - Porto',
                'verbose_name_plural': 'Lista Embarque Equipes - Portos',
                'ordering': ['idxSubTabPortoEE__idxPortoEE', '-idxSubTabPortoEE__idxPortoEE__numPS'],
            },
        ),
    ]
