# Generated by Django 4.2.7 on 2025-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0008_remove_portoembequip_descembequip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portotrocaturma',
            name='AtracPorto',
            field=models.TimeField(verbose_name='Horario da Atracação'),
        ),
    ]
