# Generated by Django 4.2.7 on 2025-10-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0008_contatouep_barcoscad_ramalbroper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatouep',
            name='unidade',
            field=models.CharField(default=0, max_length=80, verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
