# Generated by Django 4.2.7 on 2025-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0009_assunpendcontr_subassunpendcontr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunpendcontr',
            name='anexoContr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo Contratual'),
        ),
        migrations.AlterField(
            model_name='assunpendcontr',
            name='itemContr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Item Contratual'),
        ),
    ]
