# Generated by Django 4.2.7 on 2025-10-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0009_alter_portotrocaturma_atracporto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtabportoinspnorm',
            options={'ordering': ['idxsubTabPortoInspNorm__idxPortoIN__BarcoPS', '-idxsubTabPortoInspNorm__idxPortoIN__numPS'], 'verbose_name': 'Lista Inspeção Normativa - Porto', 'verbose_name_plural': 'Lista Inspeções Normativas - Portos'},
        ),
    ]
