# Generated by Django 4.2.7 on 2025-10-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0009_contatouep_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='anomSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAnomSMS', models.DateField(verbose_name='Data da Anomalia')),
                ('horaAnomSMS', models.TimeField(verbose_name='Hora da Anomalia')),
                ('relacAnomSMS', models.CharField(max_length=15, verbose_name='Referente a')),
                ('linkAnomSMS', models.CharField(max_length=15, verbose_name='Visualizar Informe')),
                ('idxAnomSMS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'Anomalia de SMS',
                'verbose_name_plural': 'Anomalias de SMS',
                'ordering': ['-dataAnomSMS', '-horaAnomSMS'],
            },
        ),
        migrations.CreateModel(
            name='desvSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorDesvSMS', models.BooleanField(default=False, verbose_name='Ocorreram Desvios?')),
                ('dataDesvSMS', models.DateField(verbose_name='Data do desvio')),
                ('localDesvSMS', models.CharField(max_length=80, verbose_name='Local do desvio')),
                ('obsDesvSMS', models.TextField(max_length=500, verbose_name='Informações Gerais')),
                ('idxDesvSMS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'Desvio de SMS',
                'verbose_name_plural': 'Desvios de SMS',
                'ordering': ['-dataDesvSMS', '-localDesvSMS'],
            },
        ),
        migrations.AlterModelOptions(
            name='inopendcontr',
            options={'ordering': ['idxInoPendContr__BarcoPS', '-idxInoPendContr__numPS'], 'verbose_name': 'Inoperância,Pendencia e Assunto Contratual', 'verbose_name_plural': 'Inoperâncias,Pendencias e Assuntos Contratuais'},
        ),
        migrations.RenameField(
            model_name='inopendcontr',
            old_name='DatainoPendContr',
            new_name='dataInoPendContr',
        ),
        migrations.RenameField(
            model_name='inopendcontr',
            old_name='DescinoPendContr',
            new_name='descInoPendContr',
        ),
        migrations.RenameField(
            model_name='inopendcontr',
            old_name='idxinoPendContr',
            new_name='idxInoPendContr',
        ),
        migrations.RenameField(
            model_name='inopendcontr',
            old_name='NumBroainoPendContr',
            new_name='numBroainoPendContr',
        ),
        migrations.RenameField(
            model_name='inopendcontr',
            old_name='previnoPendContr',
            new_name='prevInoPendContr',
        ),
        migrations.RemoveField(
            model_name='inopendcontr',
            name='BroainoPendContr',
        ),
        migrations.AlterField(
            model_name='inopendcontr',
            name='infGerContinoPendContr',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('N/A', 'N/A')], max_length=4, verbose_name='Houve Informe a Gerência de Contrato?'),
        ),
        migrations.DeleteModel(
            name='anocSMS',
        ),
        migrations.AddField(
            model_name='inopendcontr',
            name='broaInoPendContr',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO'), ('N/A', 'N/A')], default=0, max_length=4, verbose_name='Abertura de BROA?'),
            preserve_default=False,
        ),
    ]
