# Generated by Django 4.2.7 on 2025-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0010_anomsms_desvsms_alter_inopendcontr_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomsms',
            name='linkAnomSMS',
            field=models.IntegerField(verbose_name='ID do informe'),
        ),
    ]
