# Generated by Django 4.2.7 on 2025-11-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0010_alter_assunpendcontr_anexocontr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='freqLvSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaLvSeg', models.CharField(max_length=50, unique=True, verbose_name='Tema da LV')),
                ('freqLvSeg', models.IntegerField(verbose_name='Frequencia da LV (meses)')),
            ],
            options={
                'verbose_name': 'Frequencia de LV de Segurança',
                'ordering': ['temaLvSeg'],
            },
        ),
        migrations.CreateModel(
            name='LvSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LvSegCamoAsogUlt', models.DateField(verbose_name='Data da Última LV CAMO/ASOG')),
                ('LvSegCamoAsogProx', models.DateField(verbose_name='Data da Próxima LV CAMO/ASOG')),
                ('LvlSegCamoAsogFarol', models.CharField(max_length=3, verbose_name='Farol LV CAMO/ASOG')),
                ('LvSegCondNavioCpUlt', models.DateField(verbose_name='Data da Última LV Condição Navio(Curto Prazo)')),
                ('LvSegCondNavioCpProx', models.DateField(verbose_name='Data da Próxima LV Condição Navio(Curto Prazo)')),
                ('LvSegCondNavioCpFarol', models.CharField(max_length=3, verbose_name='Farol LV Condição Navio(Curto Prazo)')),
                ('LvlSegCondNavioLpUlt', models.DateField(verbose_name='Data da Última LV Condição Navio(Longo Prazo)')),
                ('LvSegCondNavioLpProx', models.DateField(verbose_name='Data da Próxima LV Condição Navio(Longo Prazo)')),
                ('LvSegCondNavioLpFarol', models.CharField(max_length=3, verbose_name='Farol LV Condição Navio(Longo Prazo)')),
                ('LvSegEspConfUlt', models.DateField(verbose_name='Data da Última LV Espaço Confinado')),
                ('LvSegEspConfProx', models.DateField(verbose_name='Data da Próxima LV Espaço Confinado')),
                ('LvSegEspConfFarol', models.CharField(max_length=3, verbose_name='Farol LV Espaço Confinado')),
                ('LvSegMovCargasUlt', models.DateField(verbose_name='Data da Última LV Movimentação de Cargas')),
                ('LvSegMovCargasProx', models.DateField(verbose_name='Data da Próxima LV Movimentação de Cargas')),
                ('LvSegMovCargasFarol', models.CharField(max_length=3, verbose_name='Farol LV Movimentação de Cargas')),
                ('LvSegPintQuimPerUlt', models.DateField(verbose_name='Data da Última LV Pintura e Produtos Químicos Perigosos')),
                ('LvSegPintQuimPerProx', models.DateField(verbose_name='Data da Próxima LV Pintura e Produtos Químicos Perigosos')),
                ('LvSegPintQuimPerFarol', models.CharField(max_length=3, verbose_name='Farol LV Pintura e Produtos Químicos Perigosos')),
                ('LvSegProcVcpUlt', models.DateField(verbose_name='Data da Última LV de Processo de VCP')),
                ('LvSegProcVcpProx', models.DateField(verbose_name='Data da Próxima LV de Processo de VCP')),
                ('LvSegProcVcpFarol', models.CharField(max_length=3, verbose_name='Farol LV de Processo de VCP')),
                ('LvlSegRespEmergUlt', models.DateField(verbose_name='Data da Última LV de Resposta a Emergência')),
                ('LvSegRespEmergProx', models.DateField(verbose_name='Data da Próxima LV de Resposta a Emergência')),
                ('LvSegRespEmergFarol', models.CharField(max_length=3, verbose_name='Farol LV de Resposta a Emergência')),
                ('LvlSegRiscSanitUlt', models.DateField(verbose_name='Data da Última LV de Risco Sanitário')),
                ('LvSegRiscSanitProx', models.DateField(verbose_name='Data da Próxima LV de Risco Sanitário')),
                ('LvSegRiscSanitFarol', models.CharField(max_length=3, verbose_name='Farol LV de Risco Sanitário')),
                ('LvSegTestHidrostUlt', models.DateField(verbose_name='Data da Última LV de Teste Hidrostático')),
                ('LvSegTestHidrostProx', models.DateField(verbose_name='Data da Próxima LV de Teste Hidrostático')),
                ('LvSegTestHidrostFarol', models.CharField(max_length=3, verbose_name='Farol LV de Teste Hidrostático')),
                ('LvlSegTrabQuentUlt', models.DateField(verbose_name='Data da Última LV de Trabalho a Quente')),
                ('LvSegTrabQuentProx', models.DateField(verbose_name='Data da Próxima LV de Trabalho a Quente')),
                ('LvSegTrabQuentFarol', models.CharField(max_length=3, verbose_name='Farol LV de Trabalho a Quente')),
                ('LvlSegTrabAltUlt', models.DateField(verbose_name='Data da Última LV de Trabalho em Altura')),
                ('LvSegTrabAltProx', models.DateField(verbose_name='Data da Próxima LV de Trabalho em Altura')),
                ('LvSegTrabAltFarol', models.CharField(max_length=3, verbose_name='Farol LV de Trabalho em Altura')),
                ('LvlSegTrabEletrUlt', models.DateField(verbose_name='Data da Última LV de Trabalho em eletricidade')),
                ('LvSegTrabEletrProx', models.DateField(verbose_name='Data da Próxima LV de Trabalho em eletricidade')),
                ('LvSegTrabEletrFarol', models.CharField(max_length=3, verbose_name='Farol LV de Trabalho em eletricidade')),
                ('obsLvSeg', models.TextField(blank=True, max_length=300, verbose_name='Observações')),
                ('idxFreqLvSeg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscweb.freqlvseg')),
                ('idxPsLvSeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'LV de Segurança',
                'verbose_name_plural': 'LVs de Segurança',
                'ordering': ['idxPsLvSeg__BarcoPS', '-idxPsLvSeg__numPS'],
            },
        ),
        migrations.CreateModel(
            name='lvSobDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRecebLvSobDemanda', models.DateField(verbose_name='Data do Recebimento')),
                ('origemLvSobDemanda', models.CharField(choices=[('AIS', 'AIS'), ('AÇÕES DE ABRANGENCIA', 'AÇÕES DE ABRANGENCIA'), ('VERIFICAR EFICÁCIA DE PLANO DE ACAO', 'VERIFICAR EFICÁCIA DE PLANO DE ACAO')], max_length=45, verbose_name='Origem')),
                ('numLvSobDemanda', models.CharField(max_length=15, verbose_name='Numero/Código da LV')),
                ('descrLvSobDemanda', models.TextField(max_length=300, verbose_name='Descrição')),
                ('linkFormsLvSobDemanda', models.CharField(max_length=100, verbose_name='Link Forms')),
                ('prazoEnvLvSobDemanda', models.DateField(verbose_name='Prazo de Envio')),
                ('statusEnvLvSobDemanda', models.CharField(choices=[('ENVIADA', 'ENVIADA'), ('A ENVIAR', 'A ENVIAR')], max_length=10, verbose_name='Status')),
                ('dataEnvioLvSobDemanda', models.DateField(verbose_name='Data do Envio')),
                ('removeDaPsLvSobDemanda', models.BooleanField(default=False, verbose_name='Remover da PS?')),
                ('idxLvSobDemanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'LV sob Demanda',
                'verbose_name_plural': 'LVs sob Demanda',
                'ordering': ['-idxLvSobDemanda__numPS', 'origemLvSobDemanda', '-numLvSobDemanda'],
            },
        ),
        migrations.RenameModel(
            old_name='smsLvMang',
            new_name='lvMangueiras',
        ),
        migrations.RemoveField(
            model_name='smslvseg',
            name='idxsmsLvSeg',
        ),
        migrations.AlterModelOptions(
            name='lvmangueiras',
            options={'ordering': ['idxLvMangueiras__BarcoPS', '-idxLvMangueiras__numPS'], 'verbose_name': 'LV de Mangueiras', 'verbose_name_plural': 'LVs de Mangueiras'},
        ),
        migrations.RenameField(
            model_name='lvmangueiras',
            old_name='idxsmsLvMang',
            new_name='idxLvMangueiras',
        ),
        migrations.DeleteModel(
            name='desvSMS',
        ),
        migrations.DeleteModel(
            name='smsLvSeg',
        ),
    ]
