# Generated by Django 4.2.7 on 2025-10-08 11:42

from django.db import migrations, models
import fiscweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0010_alter_subtabportoinspnorm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portomanutprev',
            name='Rade',
            field=models.FileField(blank=True, null=True, upload_to=fiscweb.models.caminho_PS, verbose_name='Anexo Rade'),
        ),
    ]
