# Generated by Django 4.2.7 on 2025-10-08 12:34

from django.db import migrations, models
import fiscweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0011_alter_portomanutprev_rade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portoabast',
            old_name='ObservManPrev',
            new_name='ObservAbast',
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='Anexos',
            field=models.FileField(blank=True, null=True, upload_to=fiscweb.models.caminho_PS, verbose_name='Anexos'),
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='DataHoraPrevAbast',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora Prevista'),
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='DuracPrev',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração Prevista(h)'),
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='OrdSerAbast',
            field=models.CharField(blank=True, max_length=12, verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='QuantAbast',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade (m³)'),
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='QuantUltAbast',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Ultimo Abastecimento (m³)'),
        ),
        migrations.AlterField(
            model_name='portoabast',
            name='UltAbast',
            field=models.DateField(blank=True, null=True, verbose_name='Último Abastecimento'),
        ),
    ]
