# Generated by Django 4.2.7 on 2025-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0011_alter_anomsms_linkanomsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeanomalia',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SALVO', 'Salvo'), ('ENVIADO', 'Enviado')], default='RASCUNHO', max_length=12, verbose_name='Status do Informe'),
        ),
    ]
