# Generated by Django 4.2.7 on 2025-10-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0012_informeanomalia_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentoresCestasMateriais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descContCesta', models.CharField(max_length=50, verbose_name='Descrição do Contentor/Cesta')),
                ('identContCesta', models.CharField(max_length=20, unique=True, verbose_name='Identificação do Contentor/Cesta')),
                ('dataEmbContCesta', models.DateField(verbose_name='Data de Embarque')),
                ('reqTranspContCesta', models.CharField(max_length=12, verbose_name='Número de Requisição de Transporte')),
                ('respContCesta', models.CharField(choices=[('CRD', 'CRD'), ('MIS', 'MIS'), ('EQSE', 'EQSE'), ('ISBM', 'ISBM'), ('ANC', 'ANC'), ('OUTROS', 'Outros')], max_length=10, verbose_name='Responsável')),
                ('outRespContCesta', models.CharField(blank=True, max_length=40, null=True, verbose_name='Outro Responsável')),
                ('numCertContCesta', models.CharField(max_length=20, verbose_name='Número do Certificado')),
                ('valCertContCesta', models.DateField(verbose_name='Validade do Certificado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contentor/Cesta Material',
                'verbose_name_plural': 'Contentores/Cestas Materiais',
                'ordering': ['descContCesta'],
            },
        ),
        migrations.CreateModel(
            name='materiaisOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descMat', models.CharField(max_length=50, unique=True, verbose_name='Descrição do Material')),
                ('obsDescMat', models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Operação',
                'verbose_name_plural': 'Materiais Operação',
                'ordering': ['descMat'],
            },
        ),
        migrations.CreateModel(
            name='matBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerIden', models.CharField(max_length=30, verbose_name='Número Série/Identificação')),
                ('dataReceb', models.DateField(verbose_name='Data do Recebimento')),
                ('origMat', models.CharField(choices=[('ORDEM_SERVICO', 'Ordem de Serviço'), ('UEP', 'UEP'), ('BARCO', 'Barco'), ('PORTO', 'Porto'), ('OUTROS', 'Outros')], max_length=15, verbose_name='Origem do Material')),
                ('outOrigMat', models.CharField(blank=True, max_length=40, null=True, verbose_name='Outra Origem')),
                ('respMat', models.CharField(choices=[('CRD', 'CRD'), ('MIS', 'MIS'), ('EQSE', 'EQSE'), ('ISBM', 'ISBM'), ('ANC', 'ANC'), ('OUTROS', 'Outros')], max_length=10, verbose_name='Responsável')),
                ('outRespMat', models.CharField(blank=True, max_length=40, null=True, verbose_name='Outro Responsável')),
                ('osAplicMat', models.CharField(max_length=13, verbose_name='Ordem de Serviço de Aplicação')),
                ('numReqTranspMat', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número da Requisição de Transporte')),
                ('contCestaMat', models.BooleanField(default=False, verbose_name='Está em Contentor/Cesta?')),
                ('identContCestaMat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificação do Contentor/Cesta')),
                ('numCertContCestaMat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Certificado Contentor/Cesta')),
                ('valCertContCestaMat', models.DateField(blank=True, null=True, verbose_name='Validade do Certificado Contentor/Cesta')),
                ('obsMat', models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descContCestaMat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desc_contentor', to='fiscweb.contentorescestasmateriais', verbose_name='Descrição do Contentor/Cesta')),
                ('descMat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscweb.materiaisoperacao', verbose_name='Descrição Material')),
            ],
            options={
                'verbose_name': 'Material a Bordo',
                'verbose_name_plural': 'Materiais a Bordo',
                'ordering': ['-dataReceb'],
            },
        ),
    ]
