# Generated by Django 4.2.7 on 2025-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0012_rename_observmanprev_portoabast_observabast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passserv',
            name='pdfPath',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do PDF'),
        ),
    ]
