# Generated by Django 4.2.7 on 2025-10-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0013_passserv_pdfpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portomobd',
            name='OsMobD',
        ),
        migrations.CreateModel(
            name='SubTabPortoMobD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OsMobD', models.CharField(max_length=12, verbose_name='OS de Origem')),
                ('DescMobD', models.CharField(max_length=300, verbose_name='Descrição dada OS de Mobilização ou Desmobilização')),
                ('idxSubTabPortoMobD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.passserv')),
            ],
            options={
                'verbose_name': 'MObilização e Desmobilização - Porto',
                'verbose_name_plural': 'Mobilizações Desmobilizações - Portos',
                'ordering': ['idxSubTabPortoMobD'],
            },
        ),
    ]
