# Generated by Django 4.2.7 on 2025-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0014_informeanomalia_fiscalcriador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeanomalia',
            name='municipioUF',
            field=models.CharField(choices=[('RIO DE JANEIRO-RJ', 'Rio de Janeiro – RJ'), ('MACAE-RJ', 'Macaé – RJ'), ('SAO JOAO DA BARRA_RJ', 'S. João da Barra – RJ'), ('VITORIA-ES', 'Vitória – ES'), ('BACIA DE CAMPOS-OFFSHORE', 'Bacia de Campos – Offshore'), ('BACIA DE SANTOS-OFFSHORE', 'Bacia de Santos – Offshore'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Município/UF'),
        ),
    ]
