# Generated by Django 4.2.7 on 2025-10-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscweb', '0014_remove_portomobd_osmobd_subtabportomobd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtabportomobd',
            name='idxSubTabPortoMobD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscweb.portomobd'),
        ),
    ]
